tasks:
  - init: |
      # Check if GITPOD_WORKDIR environment variable is set
      if [ -z "$GITPOD_WORKDIR" ]; then
        echo "GITPOD_WORKDIR is not set. Exiting."
        exit 1
      fi
      
      FOLDER=$GITPOD_WORKDIR
      echo "Opening folder: $FOLDER"
      
      # Change to the folder directory
      if [ -d "$FOLDER" ]; then
        cd $FOLDER
      else
        echo "Folder $FOLDER does not exist."
        exit 1
      fi
      
      # Install Miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p /home/gitpod/miniconda
      eval "$(/home/gitpod/miniconda/bin/conda shell.bash hook)"
      conda init
      
      # Check if the current folder has an environment.yml
      if [ -f environment.yml ]; then
        conda env create -f environment.yml
      else
        echo "No environment.yml found in $FOLDER."
      fi
    command: |
      eval "$(/home/gitpod/miniconda/bin/conda shell.bash hook)"
      conda activate $(head -n 1 environment.yml | cut -d' ' -f2) || echo "Environment activation failed."
