tasks:
  - init: |
      # Install Miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      bash miniconda.sh -b -p /home/gitpod/miniconda
      eval "$(/home/gitpod/miniconda/bin/conda shell.bash hook)"
      conda init
      # Check if the current folder has an environment.yml
      conda env create -f environment.yml
    command: |
      eval "$(/home/gitpod/miniconda/bin/conda shell.bash hook)"
      conda activate $(head -n 1 environment.yml | cut -d' ' -f2)
