tasks:
  - name: Install, create, and activate environment for the folders
    init: |
      curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o ~/miniconda.sh
      bash ~/miniconda.sh -b -p $HOME/miniconda
      source $HOME/miniconda/etc/profile.d/conda.sh
      echo "source $HOME/miniconda/etc/profile.d/conda.sh" >> $HOME/.bashrc
      conda init
      conda env create -f environment.yml
      conda activate
    command: |
      conda activate

